/** Instrument display names, kept out of the client-only language provider
 *  so server components (the crawler-facing <noscript> roster in the root
 *  layout) can render the same labels the app shows. */
export const INSTRUMENTS_JA: Record<string, string> = {
  piano: 'ピアノ',
  violin: 'バイオリン',
  frenchhorn: 'フレンチホルン',
  flute: 'フルート',
  clarinet: 'クラリネット',
  harp: 'ハープ',
  cello: 'チェロ',
  marimba: 'マリンバ',
  vibraphone: 'ビブラフォン',
  guitar: 'ギター',
  trumpet: 'トランペット',
  oboe: 'オーボエ',
  bass: 'ベース',
  glockenspiel: 'グロッケン',
  xylophone: 'シロフォン',
  celesta: 'チェレスタ',
  kalimba: 'カリンバ',
  koto: '琴',
  shakuhachi: '尺八',
  pipeorgan: 'パイプオルガン',
  rhodes: 'ローズピアノ',
};

export const INSTRUMENTS_EN: Record<string, string> = {
  piano: 'Piano',
  violin: 'Violin',
  frenchhorn: 'French Horn',
  flute: 'Flute',
  clarinet: 'Clarinet',
  harp: 'Harp',
  cello: 'Cello',
  marimba: 'Marimba',
  vibraphone: 'Vibraphone',
  guitar: 'Guitar',
  trumpet: 'Trumpet',
  oboe: 'Oboe',
  bass: 'Bass',
  glockenspiel: 'Glockenspiel',
  xylophone: 'Xylophone',
  celesta: 'Celesta',
  kalimba: 'Kalimba',
  koto: 'Koto',
  shakuhachi: 'Shakuhachi',
  pipeorgan: 'Pipe Organ',
  rhodes: 'Rhodes Piano',
};
